# nextcloud + mariadb + phpmyadmin
version: '3.1'

services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    command: --sql-mode='' --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: example
      MARIADB_USER: user
      MARIADB_PASSWORD: user_password
    volumes:
      - ./mariadb/data/:/var/lib/mysql/

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    ports:
      - 127.0.0.1:8080:80
    links:
      - mariadb:mariadb
      - redis:redis
    volumes:
      - ./nextcloud/:/var/www/html
    environment:
      MYSQL_PASSWORD: user_password
      MYSQL_DATABASE: example
      MYSQL_USER: user
      MYSQL_HOST: mariadb

  redis:
      image: redis:7-bullseye
      container_name: redis
      #volumes:
      #  - ./redis:/data/
      restart: always
      ports:
        - "127.0.0.1:6379:6379"
      environment:
        - TZ=Asia/Shanghai
      sysctls:
        - net.core.somaxconn=4096

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 127.0.0.1:180:80
    environment:
      PMA_HOST: mariadb
      PMA_ABSOLUTE_URI: https://127.0.0.1/
    links:
      - mariadb:mariadb

